### ISSUE TITLE
Update aeson version for stripe-http-client

### ISSUE THREAD

**Issue by eddiew** [dmjio/stripe#102]
The package specifies `aeson >=0.8 && <0.10 || >=0.11 && <1.3`, while the newest aeson is `1.4.0.0`

**Comment by dmjio** [comment]
https://github.com/dmjio/stripe/commit/505002f16a375048682c6d85004193cf2b0ede8f

**Comment by MIJOTHY** [comment]
The version looks like it was bumped to `<1.4.0` - what's the reasoning behind not allowing 1.4.0? Cheers.
