### ISSUE TITLE
`mzero` error on refunds

### ISSUE THREAD

**Issue by dariooddenino** [dmjio/stripe#105]
Hello! I'm on version 2.4.0.

When I try to refund a charge, I get this error:
`(StripeError {errorType = ParseFailure, errorMsg = "mzero", errorCode = Nothing, errorParam = Nothing, errorHTTP = Nothing})`

The transaction is actually refunded and everything looks fine on stripe side. Any idea of how I can debug this, since the error message is not helping at all?

Thanks!

**Comment by dmjio** [comment]
It looks like that (extremely unhelpful) error is originating here: https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/Types.hs#L215

The first thing we should is remove all the calls to `mzero` and replace them with `withObject`:
```haskell
instance FromJSON Refund where
   parseJSON = withObject "Refund" $ \o ->
        Refund <$> (RefundId <$> o .: "id")
               <*> o .: "amount"
               <*> o .: "currency"
               <*> (fromSeconds <$> o .: "created")
               <*> o .: "object"
               <*> o .: "charge"
               <*> o .: "balance_transaction"
               <*> o .: "metadata"
```

This way we'll at least see what field / object it failed to decode on. Another thing to do is look at the wayback machine of stripe's API docs circa 07/2014 to see if there are any fields missing / added. 

https://web.archive.org/web/20140625062328/http://stripe.com/docs/api#refunds

This looks close enough. So let's see if I did anything wrong.

<img width="1039" alt="screen shot 2018-11-12 at 5 25 12 am" src="https://user-images.githubusercontent.com/875324/48341568-65317880-e63b-11e8-82f3-33d4f5291b0a.png">

So far it all looks good, the `balance_transaction` field might have been expanded though, this means a `BalanceTransaction` could have failed to parse.

https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/Types.hs#L1564

and docs https://web.archive.org/web/20140625062328/http://stripe.com/docs/api#balance

So, I'd continue on this route...

**Comment by dariooddenino** [comment]
Thanks for the info! I will check what's failing to parse as soon as I have some time :)

**Comment by dmjio** [comment]
@dariooddenino another thing we could do is check your stripe API logs, and try to decode them into the `Refund` type. Go to https://dashboard.stripe.com/<account>/logs and try to find the response body you received and paste it here.

**Comment by dmjio** [comment]
#109
