### ISSUE TITLE
cardCountry is not required - causes parse failures on successful charges (and presumably other problems)

### ISSUE THREAD

**Issue by dbp** [dmjio/stripe#19]
The field "country" is not guaranteed to be present in cards. I've only ever seen this with AmEx, but maybe other types of cards can be country-less too. It was a bit of deja-vu when I started getting these errors today, as I fixed this same issue in the previous stripe library: https://github.com/michaelschade/hs-stripe/commit/a3ca41cbc8c54d0a151f370b9012c0d776acc35e

This is a really serious issue, as it means that charges that succeeded (and charged the customers card) will not be able to be understood by the application. In particular, there is no way of refunding them, because we don't have the id (since it didn't parse). 

The fix is easy - I changed the code here: https://github.com/dbp/stripe/commit/b25001c3dd8c8cdaa8361c8cc84a78292a9734ca , but there are probably tests that need to be fixed so I don't want ot add a pull request as is (and it's pretty early right now...)

**Comment by dmjio** [comment]
@dbp, that may have been true of the 2011 API, but as of 2014 there is no indication on the docs that Country is optional (They explicitly mark fields as optional).

```
country string
Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you’ve collected.
```

For confirmation I'm adding @matthewarkin. @matthewarkin can you confirm country code is/isn't optional.

**Comment by dbp** [comment]
@dmjio Well I have an example of the 2014-10-07 API returning null for the country in the card, embedded within a charge... I'm not sure what else to tell you. If it weren't sensitive information, I'd paste it in here :)

**Comment by dmjio** [comment]
Ok, yea, stripe can be pretty terrible about documenting their API. That's pretty unfortunate there isn't more info regarding that. I'll make an issue.

**Comment by matthewarkin** [comment]
So the payment country is determined by the BIN number of the card and it ~should~ always be there, but I have heard cases where it isn't always there. I don't necessarily know why, but a null-able string would be a decent type for country.

**Comment by matthewarkin** [comment]
I'm told some international Amex cards don't have a country associated with them. Don't you love payments?

**Comment by dmjio** [comment]
Soon we'll be writing APIs for type safe bitcoin payments and we'll look back on this and laugh. @dbp Stripe's api's are pretty ad-hoc I'm assuming the reason there is no standard specification for us to code against is that they themselves aren't sure of all the rules, nuances.

**Comment by dbp** [comment]
@matthewarkin I've now seen this at least twice (well, twice it has caused errors so I've noticed it), and both times it was an Amex card from someone outside the US, so what you say makes sense.

**Comment by dmjio** [comment]
Should be fixed in https://github.com/dmjio/stripe/pull/64
