### ISSUE TITLE
Tests Broken on hackage version?

### ISSUE THREAD

**Issue by tdimiduk** [dmjio/stripe#22]
The version of stripe-haskell on hackage (and nixpkgs) does not appear to be able to run its tests. I took the tarball from hackage and ran:
cabal clean 
cabal configure --enable-tests
cabal build tests

In-place registering stripe-haskell-0.1.4.0...
Preprocessing test suite 'tests' for stripe-haskell-0.1.4.0...

tests/Main.hs:6:18:
    Could not find module ‘Test.Config’
    Use -v to see a list of the files searched for.

tests/Main.hs:7:18:
    Could not find module ‘Test.Account’
    Use -v to see a list of the files searched for.
<further similar output snipped>

Do I have something uniquely wrong in my setup, or are the tests broken in general on the hackage version?

**Comment by dmjio** [comment]
Nothing wrong on your part, it seems the tests have not been included in any hackage release starting from the initial release. Unsure why this is. I've still been able to use it fine from nixpkgs.

**Comment by dmjio** [comment]
We're on the cusp of a new release, with new tests.

**Comment by tdimiduk** [comment]
Do you do anything special to get it to install with nixpkgs? For me it try
to run the tests and then gives up on installing when the tests fail.

**Comment by dmjio** [comment]
I forgot to add Test.* modules to the test modules section. Will add and
put up a new hackage version tonight.

On Tue, Jul 14, 2015 at 6:48 PM, Tom Dimiduk <notifications@github.com>
wrote:

> Do you do anything special to get it to install with nixpkgs? For me it try
> to run the tests and then gives up on installing when the tests fail.
>
> On Tue, Jul 14, 2015 at 6:02 PM, David Johnson <notifications@github.com>
> wrote:
>
> > We're on the cusp of a new release, with new tests.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dmjio/stripe/issues/22#issuecomment-121405234>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmjio/stripe/issues/22#issuecomment-121430360>.
>



-- 
Cell: 1.630.740.8204

**Comment by dmjio** [comment]
@tdimiduk, `0.1.4.1` is on hackage and should contain the tests (modules now present in the `other-modules` section of the test-suite portion). Tests only get run if you `export STRIPEKEY=<test-key>`. Otherwise they won't run, but return success (so nix will work regardless of the variable being set). Hope this helps!

**Comment by tdimiduk** [comment]
Great. Thanks for fixing this so quickly! I have submitted a PR to nixpkgs to get this new version in.

**Comment by dmjio** [comment]
Fantastic thanks, let me know if you run into anything else.
