### ISSUE TITLE
Stripe version

### ISSUE THREAD

**Issue by TheunisKotze** [dmjio/stripe#24]
Would be good to state the version of stripe this library is compatible with in the readme & docs.  Had to go searching through the source code to find it.

How were you thinking of supporting multiple stripe versions?  For example, I need to use functionality introduced in [2015-02-18](https://stripe.com/docs/upgrades#2015-02-18).  I haven't yet looked in depth how much of the rest of the api has changed between your version and this (or the newest) version

**Comment by LukeHoersten** [comment]
Basically the way the Stripe people do it is just adding more things into the JSON objects so typically you can use a newer version of the API with the current code. That's what most people do in fact. Then you just use the config to override the version requested. Also, the version pegging in the Stripe dashboard overrides the version requested in the API.

If you want to submit a PR better documenting the default version request that would be nice :).

**Comment by dmjio** [comment]
@TheunisKotze what features from 2015 are you looking to use? If it's a new endpoint it may be accessible via our API version (i.e bitcoin functionality came out later than this API version, but we can still get access to it).

If you need a custom parser to handle the new request I recommend using the `stripeRaw` function. It let's you define your own ADT and parser in the case of new functionality.

**Comment by TheunisKotze** [comment]
Thanks for the tips.  The change from cards to sources is what interests me.  
I'll take a more thorough look and post an update

**Comment by dmjio** [comment]
@TheunisKotze, yea the API changelog is interesting
> Older API versions return both the card attribute and the source attribute.

We should still have access to `source` here it seems, unsure if this helps though. Keep me posted.

**Comment by dmjio** [comment]
Added in https://github.com/dmjio/stripe/commit/540b580813a2f243856b5a32a04737287a1e2f93
