### ISSUE TITLE
How to charge by token from Stripe Checkout?

### ISSUE THREAD

**Issue by tdimiduk** [dmjio/stripe#28]
I had code working in version 1.4 which used chargeCardByToken to charge a token I got from the Stripe Checkout api, but this function appears to be missing in version 2. Is there a way to replicate this functionality in the new version? 

The old function was:
```haskell
chargeCardByToken :: TokenId -> Currency -> Amount -> Maybe Description -> Stripe Charge
```

**Comment by andrewthad** [comment]
I'm having the same problem.

**Comment by dmjio** [comment]
The following should work:
```haskell
chargeCardByToken :: TokenId -> Currency -> Amount -> IO (Either StripeError Charge)
chargeCardByToken tokenId currency amount = 
   stripe config $ createCharge amount currency
      -&- tokenId
```

**Comment by dmjio** [comment]
@andrewthad @tdimiduk polite ping :) 

Can this issue be closed?
