### ISSUE TITLE
Exception instance for StripeError

### ISSUE THREAD

**Issue by andrewthad** [dmjio/stripe#32]
Can you add an instance for `Exception` to `StripeError`?

**Comment by dmjio** [comment]
@andrewthad https://github.com/dmjio/stripe/pull/33, if it looks good to you I can merge it. cc @stepcut

**Comment by andrewthad** [comment]
Yeah, that's exactly what I had in mind.

**Comment by dmjio** [comment]
Will push to hackage soon
