### ISSUE TITLE
cancelSubscription with AtPeriodEnd True

### ISSUE THREAD

**Issue by tlaitinen** [dmjio/stripe#38]
The instance `ToStripeParam AtPeriodEnd` at
https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/StripeRequest.hs#L164-L166

looks a bit suspicious because it's identical to `ToStripeParam Prorate` and IMO Stripe API expects `at_period_end`. 

I changed this locally, but Stripe backend still doesn't like the request sent by
https://github.com/dmjio/stripe/blob/master/stripe-tests/tests/Web/Stripe/Test/Subscription.hs#L132 
and says that the DELETE request had no body:

<img width="763" alt="screen shot 2016-04-18 at 12 51 16" src="https://cloud.githubusercontent.com/assets/1113883/14600376/efb912fc-0564-11e6-9fe9-6d35ded0a87c.png">

**Comment by tlaitinen** [comment]
I modified ```Web.Stripe.Client.HttpStreams``` to print the request headers and body. I also removed the version parameter to test if it had any effect.

The following HTTP request (auth changed) was not parsed by the Stripe backend:
```
DELETE /v1/customers/cus_8GhhrGWog3smpa/subscriptions/sub_8IASz0WSQUFsj8 HTTP/1.1
Host: api.stripe.com
Authorization: Basic XXXXXXXXXXXXXXXXXXXX
Accept-Encoding: gzip
Content-Type: application/x-www-form-urlencoded
Connection: Keep-Alive

at_period_end=true
```

I pasted the text above in a text file, added another header ```Content-Length: 18```, and fed it to ```ncat --ssl api.stripe.com 443```. Then the request was properly parsed at Stripe backend.

**Comment by tlaitinen** [comment]
https://github.com/tlaitinen/stripe/commit/e9967417dd07ce113bbaad472a94b54980d79d66 fixes the issue.

**Comment by dmjio** [comment]
@tlaitinen thanks again for this change!
