### ISSUE TITLE
test suite failures (106 examples, 20 failures)

### ISSUE THREAD

**Issue by tlaitinen** [dmjio/stripe#39]
See full log at http://pastebin.com/mFZAkw13

**Comment by tlaitinen** [comment]
Actually, the only real failure is:

```tests/Web/Stripe/Test/Event.hs:13:
      20) Event tests Succesfully retrieves events
           tests/Web/Stripe/Test/Event.hs:15:
           predicate failed on: Left (StripeError {errorType = ParseFailure, errorMsg = "key \"card\" not present", errorCode = Nothing, errorParam = Nothing, errorHTTP = Nothing})```

**Comment by dmjio** [comment]
@tlaitinen, thanks for this. I do believe the `Events` API is the only part of Stripe's API where the version in your dashboard takes precedence over the one specified in the request. Which just means the JSON returned for an Event would be based on a newer API, potentially causing a parse failure. Can you check your dashboard to see what API version you're on. @matthewarkin might be able to confirm this as well.

**Comment by tlaitinen** [comment]
It says that the API version is 2016-03-07 (latest).

**Comment by matthewarkin** [comment]
The event object itself will correspond to the API version specified, but the problem is the `object` of the event object will be formatted in your dashboard version.

Since the error is specifying card not being set, I'm assuming that this library is before the big card -> sources shift.

**Comment by tlaitinen** [comment]
Is someone working on this? If not, then I can have a look at this.

**Comment by dmjio** [comment]
@tlaitinen, sounds good. I think the only thing to do is ignore the tests for events since it isn't governed by the API version specified in the request header.

**Comment by tlaitinen** [comment]
I'm interested in parsing the events correctly sent by the latest API 2016-03-07. It does not seem possible to downgrade to an older version of the API. I wonder if I can just modify Event and the corresponding FromJSON instances and have it work.

**Comment by tlaitinen** [comment]
The commits https://github.com/dmjio/stripe/commit/ed087cfe21d47d6840cb3fdb141f9d65b172face https://github.com/dmjio/stripe/commit/0ddf4ca361484d4ef63cb10c70df15be78c7a81f and https://github.com/dmjio/stripe/commit/577044368d4e1319f7192814ab0af87d72d4c425 fix the webhook parsing for a few event types. However, they probably cannot be merged upstream because users may be using an older version of the API.

**Comment by whittle** [comment]
I’m also running into this issue.

**Comment by dmjio** [comment]
@whittle it seems you may have to use a custom json parser for events now, since, according to @matthewarkin,
> the problem is the object of the event object will be formatted in your dashboard version.
If your dashboard version is greater than 2014 (which I assume it is), then the events returned will be of a different version.

**Comment by dmjio** [comment]
`Events API` is a black sheep since it is the only API endpoint where you cannot use version `2014`. This is because you are receiving an async notification and there is no way to specify a version other than what is in your dashboard. I'd recommend keeping your dashboard to an old API version, or writing your own custom parser to be used which is possible with the `*-raw` functions.
