### ISSUE TITLE
UpdateSubscription

### ISSUE THREAD

**Issue by bitemyapp** [dmjio/stripe#41]
Having a hard time understanding what UpdateSubscription is meant to do. It takes a subscription id rather than a value as an argument, implying you're supposed to create a new subscription and then swap the customer over to that.

However, the documentation doesn't say one way or the other: 
![screenshot from 2016-04-18 15-39-20](https://cloud.githubusercontent.com/assets/320177/14619167/be335884-057b-11e6-9aee-0d60eac95087.png)

I look at the Stripe docs for what happens when you change a subscription plan: https://support.stripe.com/questions/handling-subscription-changes

But it's unclear if they meant the Indiana Jones bagswap UpdateSubscription _seems_ to point to or something not seemingly supported in the Subscription module.

**Comment by dmjio** [comment]
Yea, it is unclear. We've changed the way we handle optional parameters in records to use typeclasses instead (@stepcut 's approach) and it's pretty slick. So the fields that are eligible for updates are here: 
http://hackage.haskell.org/package/stripe-core-2.0.2/docs/Web-Stripe-Subscription.html#t:UpdateSubscription

And to annotate the `UpdateSubscription` with what you want to update you'd use the `-&-` combinator.

So something like this:

```haskell
let req = updateSubscription customerId subscriptionId 
                  -&- Quantity 10
                  -&- Prorate True
```
Business logic in the type system, FTW.

Lastly, the Stripe docs have changed a lot, and the backlog isn't too illuminating IIRC.

**Comment by dmjio** [comment]
@bitemyapp but yea, to answer the original question, the `CustomerId` and `SubscriptionId` are meant to identify a single subscription (if it exists), and then the `HasParam` instances are what can be updated on that single subscription. If it doesn't exist, it will probably just `Left` error on you. But yea, everything in that link /also/ happens, so caveat emptor.

**Comment by bitemyapp** [comment]
@dmjio the HasParam thing seems counter-productively implicit to me. I had no idea from the types, documentation, `:info`, anything that this was a thing or that I needed to use `-&-` and the fields to specify new data.

**Comment by dmjio** [comment]
Yea, we need to document it better in the examples. Some examples demonstrate usage though, http://hackage.haskell.org/package/stripe-core-2.0.2/docs/Web-Stripe-Coupon.html

**Comment by dmjio** [comment]
`:info` on `UpdateSubscription` should give you the instances though, let me know if it doesn't.

**Comment by dmjio** [comment]
Going to close this issue. There is another issue that provides links to a blog post on how to use `-&-`
