### ISSUE TITLE
What is 'object' and why does it keep clashing with my Aeson stuff?

### ISSUE THREAD

**Issue by bitemyapp** [dmjio/stripe#42]
![screenshot from 2016-04-19 15-33-49](https://cloud.githubusercontent.com/assets/320177/14654640/51471912-0644-11e6-9a01-47f6afe93647.png)

Keep having to do this to avoid ambiguous imports.

**Comment by dmjio** [comment]
It's from `StripeList`, which is how stripe performs pagination. `object` identifies the kind of json object this is, seems like an internal stripe thing. Maybe @matthewarkin can comment on `object`
```haskell
data StripeList a = StripeList {                                                                                                                                                  
      list       :: [a]                                                                                                                                                           
    , stripeUrl  :: Text                                                                                                                                                          
    , object     :: Text                                                                                                                                                          
    , totalCount :: Maybe Int                                                                                                                                                     
    , hasMore    :: Bool                                                                                                                                                          
    } deriving (Read, Show, Eq, Ord, Data, Typeable)   
```

**Comment by dmjio** [comment]
The `object` field is common to most stripe JSON responses. We could probably have named it differently to avoid the clash though. Would be a moderately large breaking change of course. Although I doubt there is much usage of that field.

**Comment by dmjio** [comment]
@bitemyapp do you want me to rename it to something else? :)

**Comment by bitemyapp** [comment]
@dmjio >do you want me to rename it to something else? :)

Having thought about it yes, but only on the next major version so it's rolled in with something else.

**Comment by dmjio** [comment]
@bitemyapp how does `stripeObject` sound?

**Comment by bitemyapp** [comment]
@dmjio lurvely.
