### ISSUE TITLE
Tedious imports

### ISSUE THREAD

**Issue by bitemyapp** [dmjio/stripe#52]
![screenshot from 2016-10-14 16-01-18](https://cloud.githubusercontent.com/assets/320177/19402594/796ba344-9227-11e6-83d1-a9b18f9f2ba2.png)

This really should not be an error when I was already importing `Web.Stripe`. Is there an import that gathers everything together which I am missing?

**Comment by dmjio** [comment]
`Web.Stripe.Errors` should be getting re-exported but it isn't.

**Comment by 3noch** [comment]
Re-exported from what?

**Comment by dmjio** [comment]
from `Web.Stripe`

**Comment by dmjio** [comment]
https://github.com/dmjio/stripe/pull/63
