### ISSUE TITLE
Exapnded___ ADT Pattern for CustomerId, ChargeId etc seems inelegant

### ISSUE THREAD

**Issue by maxcan** [dmjio/stripe#6]
For types like CustomerId and ChargeId I don't see the value of the pattern:

``` haskell
data ChargeId
  = ChargeId Text
  | ExpandedCharge Text
```

It principally throws me off in writing `ToJSON` and `PersistField` instances.  Could a `Customer` record really contain another `Customer` record in the `customerId` field?  It seems like we're going out of are way to allow illegal states.

The other stripe library, which I am trying to migrate from since this one has a lot going for it uses newtypes for types like CouponId, ChargeId, CustomerId, etc.  This is great for type safety and I don't quite understand the value of the Expanded___ ADT pattern.

**Comment by dmjio** [comment]
It seems that @stepcut has added his recommendations to this project, and this issue can therefore be closed.
