### ISSUE TITLE
Clarification on running tests

### ISSUE THREAD

**Issue by bchase** [dmjio/stripe#74]
Hi! I'm rather new to Haskell, and am hoping to fork and extend this library to use a more current Stripe API version (I mostly just need Connect and Bank Accounts), but I cannot quite figure out how to run the tests.

I noticed the `default.nix` file at the project root, installed Nix, and successfully ran `nix-build`, which appears to have compiled everything, but now I'm unsure of where and how to run the `cabal` commands listed in the README.

So I guess my question is: what do I do next?

Apologies in advance for such a vague newbie question, but I would _really_ appreciate any help you could offer.

Also, thanks for maintaining what appears to be a really great Stripe package! :+1:

**Comment by dmjio** [comment]
Hi @bchase, thanks for the kind words, and thanks taking initiative on this. Apologies there isn't better documentation for contributors yet. In regards to running the tests, I'd run them from the `stripe-http-streams` package. To do that I'd first build that package using the following command:

```nix
nix-build -A stripe-http-streams
```

And then inspecting the `result` folder, the tests should be present in there, and runnable. But, if you build the `stripe-haskell` package directly (using `nix-build -A stripe-haskell`) the tests will be run automatically, although you won't see the test output (afaik). This is actually what our build does on `TravisCI` https://github.com/dmjio/stripe/blob/master/.travis.yml#L29.

For tackling connect, I'd recommend using the old API docs (for 2014), to ensure stability with this API. https://web.archive.org/web/20141111004924/https://stripe.com/connect

I'd also look at what @LukeHoersten did in the other stripe package (since he added connect to it), and see if we can glean something from that work.

https://github.com/michaelschade/hs-stripe/blob/master/src/Web/Stripe/Connect.hs

**Comment by dmjio** [comment]
Also, to be in an environment, where you can build `stripe-http-streams`, with the tests. I'd call,
```nix-shell -A stripe-http-streams.env```
then call
```
cabal configure --enable-tests
cabal build
./dist/build/tests/tests
```

**Comment by bchase** [comment]
Awesome! Thanks @dmjio. I'll give this a try and report back! :slightly_smiling_face:

**Comment by dmjio** [comment]
@bchase 🍻

**Comment by bchase** [comment]
It worked! :raised_hands: 

## Nix

I found that it does only show `PASS` for the success case:

```
ubuntu@ubuntu-xenial:~/haskell/stripe$ nix-build -A stripe-http-streams

[... snip ...]

Preprocessing test suite 'tests' for stripe-http-streams-2.2.1...
[1 of 1] Compiling Main             ( tests/Main.hs, dist/build/tests/tests-tmp/Main.dyn_o )
Linking dist/build/tests/tests ...
running tests
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to: dist/test/stripe-http-streams-2.2.1-tests.log
1 of 1 test suites (1 of 1 test cases) passed.

[... snip ...]

/nix/store/f1p9b5d5f7d0ra03hj647hcz5v69xrjv-stripe-http-streams-2.2.1
```

But for the failure case it lists the whole suite of tests, marks the failures, and shows what failed:

```
ubuntu@ubuntu-xenial:~/haskell/stripe$ nix-build -A stripe-http-streams

[... snip ...]

Preprocessing test suite 'tests' for stripe-http-streams-2.2.1...
[1 of 1] Compiling Main             ( tests/Main.hs, dist/build/tests/tests-tmp/Main.dyn_o )
Linking dist/build/tests/tests ...
running tests
Running 1 test suites...
Test suite tests: RUNNING...

[... snip ...]

Card tests
  Can create a Customer and add a Card by CardNumber
  Can create a Customer Card by TokenId
  Can retrieve a Customer Card
  Can retrieve a Customer's Card with expansion
  Can retrieve a Customer's Cards
  Can retrieve a Customer's Cards with Expansion
  Can delete a Customer's Cards
  Can update a Customer's Card FAILED [1]

[... snip ...]

Failures:

  tests/Web/Stripe/Test/Card.hs:110:
  1) Card tests Can update a Customer's Card
       expected: Just (Name {getName = "badCardName"})
        but got: Just (Name {getName = "cardName"})

Randomized with seed 644267837

Finished in 204.7676 seconds
87 examples, 1 failure
Test suite tests: FAIL
Test suite logged to: dist/test/stripe-http-streams-2.2.1-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/h3wyr46p4zyrcrdhhrfc0n8dyigfza79-stripe-http-streams-2.2.1.drv’ failed with exit code 1
error: build of ‘/nix/store/h3wyr46p4zyrcrdhhrfc0n8dyigfza79-stripe-http-streams-2.2.1.drv’ failed
```

## Cabal

I couldn't figure out how to get the `cabal build` version to work though, as I ran into the following errors:

```
ubuntu@ubuntu-xenial:~/haskell/stripe$ nix-shell -A stripe-http-streams.env

[nix-shell:~/haskell/stripe]$ cd stripe-http-streams/

[nix-shell:~/haskell/stripe/stripe-http-streams]$ cabal configure --enable-tests
Resolving dependencies...
Configuring stripe-http-streams-2.2.1...

[nix-shell:~/haskell/stripe/stripe-http-streams]$ cabal build
Building stripe-http-streams-2.2.1...
Preprocessing library stripe-http-streams-2.2.1...

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead
In-place registering stripe-http-streams-2.2.1...
cabal:
'/nix/store/q1jm1lk9z5kgm2jga2k2vjqb5k45c9j3-ghc-8.0.2-with-packages/bin/ghc-pkg'
exited with an error:
stripe-http-streams-2.2.1: Warning: haddock-interfaces:
/home/ubuntu/haskell/stripe/stripe-http-streams/dist/doc/html/stripe-http-streams/stripe-http-streams.haddock
doesn't exist or isn't a file
stripe-http-streams-2.2.1: Warning: haddock-html:
/home/ubuntu/haskell/stripe/stripe-http-streams/dist/doc/html/stripe-http-streams
doesn't exist or isn't a directory
stripe-http-streams-2.2.1: installed package info from too old version of
Cabal (key field does not match id field)
```

This assumes that I should be in `stripe-http-streams/` to run the `cabal` commands, which I'm not sure about. The project root didn't have a `.cabal` file though, so I figured that couldn't be it.

## Success!

So that answers my question! Your `nix-build` suggestion gets me what I needed. Thanks so much for the help!

Also, do you think that updating the README to explain how to use this `nix-build` version would be better? I'd be happy to make a PR for it, if you'd like.

**Comment by dmjio** [comment]
@bchase fantastic :) 

The haddock issue is troubling, and it might be a problem with nix itself, when it constructs the immutable `ghc-pkg` list.

Any PR's to update documentation regarding `nix-build` would be awesome. In fact, if you wanted to go ahead and write `Contributing.md` I'd gladly accept it.

**Comment by dmjio** [comment]
Closing for now, reopen if necessary.
