### ISSUE TITLE
Symlink README to stripe-haskell/README

### ISSUE THREAD

**Issue by nmattia** [dmjio/stripe#82]
The README.md has the following snippet:

``` haskell
import Web.Stripe
import Web.Stripe.Coupon

main :: IO ()
main = do
  let config = StripeConfig "secret key"
  result <- stripe config $ updateCoupon (CouponId "couponid") [("key1", "value2"), ("key2", "value2")]
  case result of
    Right coupon -> print $ couponMetaData coupon
    Left stripeError -> print stripeError
```

which doesn't compile, because `StripeKey` has no `IsString` instance. As I was submitting a PR, I realized that @bitemyapp had already fixed it for `stripe-haskell/README.md` in 538aae94e812a050698bbd432af2ec6b0fc58cb1. Both READMEs look very similar, maybe symlink one to the other?

**Comment by dmjio** [comment]
https://github.com/dmjio/stripe/commit/1ee34815549473614c9dcdd77f8ce9f3e305bf33
