### ISSUE TITLE
Retrieving all subscriptions

### ISSUE THREAD

**Issue by nmattia** [dmjio/stripe#83]
The Stripe API allows [retrieving _all_ subscriptions](https://stripe.com/docs/api/curl#list_subscriptions), _i.e._ not only those associated with a particular customer ID. However the `stripe-haskell` library only allows retrieving subscriptions by customer ID:

https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/Subscription.hs#L189

I've created a fork where I can retrieve all the subscriptions: https://github.com/dmjio/stripe/compare/master...nmattia:nm/retrieve-all-subsc

While this works (and passes the tests), and while another function could be written to retrieve subscriptions by customer ID (`getCustomerSubscriptions`), this is unfortunately a breaking change. Let me know if you see a nice (or at least acceptable) way of introducing the API call and I'll happily submit a PR.

**Comment by dmjio** [comment]
Renaming `getSubscriptions` to `getSubscriptionsByCustomerId`, and then introducing 
```haskell
getSubscriptions :: StripeRequest GetSubscriptions
```
would be totally fine with me.
