### ISSUE TITLE
Add support for http-client

### ISSUE THREAD

**Issue by nmattia** [dmjio/stripe#90]
This library has a wonderful pure core module. It should be straightforward to use the widely used [http-client](https://hackage.haskell.org/package/http-client-0.5.8) library.

**Comment by dmjio** [comment]
@nmattia I'd gladly remove `http-streams` in favor of `http-client`, wouldn't be opposed to reconciling all packages back into one either.

**Comment by dmjio** [comment]
@nmattia for now, maybe an `http-client` backend would suffice, we could make it the default.

**Comment by creichert** [comment]
I have an `http-client` backend I've used across multiple projects for a while now. It's really simple and completely API compatible w/ `stripe-http-streams`. This has helped me lower the dep profile of projects and reuse existing http-client(-tls) related libs i was already using. 

My current plan is to check-in the `stripe-http-client` backend first. Then, in a separate PR I want to add a cabal flag to `stripe-haskell` to switch the backend between http-client and http-streams, maintaining the current set of defaults.

I'll try to do this in a hurry as the module itself is completely ready 2 go.

**Comment by dmjio** [comment]
Sounds fantastic, I’ll merge when ready. Also, I would not at all be opposed to making http-client the default backend for stripe-haskell.
